# Don't change this! Version used to track needed updates.
version = 3
enableSpellPowerScaling = true
spellScalingDiminishingReturnsStart = 1.4
spellScalingDiminishingReturnsStrength = 10.0

[spellPowerApi]
enableWeaponAttributes = true
scalingMultiplier = 0.5

[spellPowerApi.weaponSpellPowerBonuses]
"simplyswords:brimstone_claymore" = 4.0
"simplyswords:watcher_claymore" = 4.0
"simplyswords:the_devourer" = 4.0
"simplyswords:storms_edge" = 2.0
"simplyswords:stormscale" = 2.0
"simplyswords:ionbound_stormscale" = 2.0
"simplyswords:stormbringer" = 2.0
"simplyswords:bramblethorn" = 2.0
"simplyswords:watching_warglaive" = 2.0
"simplyswords:toxic_longsword" = 3.75
"simplyswords:emberblade" = 2.0
"simplyswords:hearthflame" = 4.0
"simplyswords:soulkeeper" = 4.0
"simplyswords:twisted_blade" = 4.0
"simplyswords:soulstealer" = 2.0
"simplyswords:soulrender" = 4.0
"simplyswords:soulstalker" = 4.0
"simplyswords:soulpyre" = 4.0
"simplyswords:frostfall" = 2.0
"simplyswords:molten_edge" = 2.0
"simplyswords:livyatan" = 2.0
"simplyswords:icewhisper" = 4.0
"simplyswords:arcanethyst" = 4.0
"simplyswords:thunderbrand" = 4.0
"simplyswords:mjolnir" = 2.0
"simplyswords:slumbering_lichblade" = 4.0
"simplyswords:waking_lichblade" = 4.0
"simplyswords:awakened_lichblade" = 4.0
"simplyswords:shadowsting" = 2.0
"simplyswords:dormant_relic" = 2.0
"simplyswords:righteous_relic" = 2.0
"simplyswords:tainted_relic" = 2.0
"simplyswords:sunfire" = 2.0
"simplyswords:harbinger" = 2.0
"simplyswords:whisperwind" = 4.0
"simplyswords:dreadwhisper" = 4.0
"simplyswords:emberlash" = 2.0
"simplyswords:waxweaver" = 2.0
"simplyswords:hiveheart" = 2.0
"simplyswords:stars_edge" = 2.0
"simplyswords:wickpiercer" = 2.0
"simplyswords:gloampiercer" = 2.0
"simplyswords:tempest" = 2.0
"simplyswords:flamewind" = 2.0
"simplyswords:magiscythe" = 2.0
"simplyswords:enigma" = 2.0
"simplyswords:magispear" = 2.0
"simplyswords:magiblade" = 2.0
"simplyswords:caelestis" = 2.0
"simplyswords:dawnquiver" = 4.0
"simplyswords:riftmane" = 4.0
"simplyswords:wraithfang" = 2.0
"simplyswords:wraithmaw" = 2.0
"simplyswords:bloodwake" = 2.0
"simplyswords:chompolotl" = 2.0

[spellPowerApi.weaponAbilitySchools]
"simplyswords:brimstone_claymore" = "spell_power:fire"
"simplyswords:watcher_claymore" = "spell_power:healing"
"simplyswords:the_devourer" = "eternal_attributes:unholy"
"simplyswords:storms_edge" = "spell_power:lightning"
"simplyswords:stormscale" = "spell_power:lightning"
"simplyswords:awakened_stormscale" = "spell_power:lightning"
"simplyswords:ionbound_stormscale" = "spell_power:lightning"
"simplyswords:stormbringer" = "spell_power:lightning"
"simplyswords:bramblethorn" = "spell_power:healing"
"simplyswords:watching_warglaive" = "spell_power:healing"
"simplyswords:toxic_longsword" = "eternal_attributes:unholy"
"simplyswords:emberblade" = "spell_power:fire"
"simplyswords:hearthflame" = "spell_power:fire"
"simplyswords:soulkeeper" = "spell_power:soul"
"simplyswords:twisted_blade" = "spell_power:soul"
"simplyswords:soulstealer" = "spell_power:soul"
"simplyswords:soulrender" = "spell_power:soul"
"simplyswords:soulstalker" = "spell_power:soul"
"simplyswords:soulpyre" = "spell_power:soul"
"simplyswords:frostfall" = "spell_power:frost"
"simplyswords:molten_edge" = "spell_power:fire"
"simplyswords:livyatan/frost" = "spell_power:frost"
"simplyswords:livyatan/lightning" = "spell_power:lightning"
"simplyswords:icewhisper" = "spell_power:frost"
"simplyswords:arcanethyst" = "spell_power:arcane"
"simplyswords:thunderbrand" = "spell_power:lightning"
"simplyswords:mjolnir" = "spell_power:lightning"
"simplyswords:slumbering_lichblade" = "eternal_attributes:unholy"
"simplyswords:waking_lichblade" = "eternal_attributes:unholy"
"simplyswords:awakened_lichblade" = "eternal_attributes:unholy"
"simplyswords:shadowsting" = "spell_power:soul"
"simplyswords:righteous_relic/damage" = "spell_power:fire"
"simplyswords:righteous_relic/healing" = "spell_power:healing"
"simplyswords:sunfire/damage" = "spell_power:fire"
"simplyswords:sunfire/healing" = "spell_power:healing"
"simplyswords:tainted_relic" = "spell_power:soul"
"simplyswords:harbinger" = "spell_power:soul"
"simplyswords:whisperwind" = "spell_power:arcane"
"simplyswords:dreadwhisper" = "spell_power:soul"
"simplyswords:emberlash" = "spell_power:fire"
"simplyswords:waxweaver" = "spell_power:fire"
"simplyswords:hiveheart" = "spell_power:healing"
"simplyswords:stars_edge" = "spell_power:arcane"
"simplyswords:wickpiercer" = "spell_power:fire"
"simplyswords:gloampiercer" = "spell_power:soul"
"simplyswords:tempest/fire" = "spell_power:fire"
"simplyswords:tempest/frost" = "spell_power:frost"
"simplyswords:flamewind" = "spell_power:fire"
"simplyswords:magiscythe" = "spell_power:arcane"
"simplyswords:enigma" = "spell_power:arcane"
"simplyswords:magispear" = "spell_power:arcane"
"simplyswords:magiblade" = "spell_power:arcane"
"simplyswords:caelestis" = "spell_power:arcane"
"simplyswords:dawnquiver" = "spell_power:healing"
"simplyswords:riftmane" = "spell_power:arcane"
"simplyswords:wraithfang" = "spell_power:soul"
"simplyswords:wraithmaw" = "spell_power:soul"
"simplyswords:bloodwake" = "eternal_attributes:blood"
"simplyswords:chompolotl" = "spell_power:frost"
"simplyswords:dreadtide" = "spell_power:soul"

[spellPowerApi.gemPowerSchools]
"simplyswords:banehead_swarm" = "spell_power:soul"
"simplyswords:dancing_blades" = "spell_power:arcane"
"simplyswords:dragon_maw" = "spell_power:fire"
"simplyswords:evocation" = "eternal_attributes:unholy"
"simplyswords:faultline" = "spell_power:healing"
"simplyswords:goat_stampede" = "spell_power:healing"
"simplyswords:imbued" = "spell_power:arcane"
"simplyswords:immolation" = "spell_power:fire"
"simplyswords:necromantic_arsenal" = "spell_power:soul"
"simplyswords:radiance" = "spell_power:fire"
"simplyswords:runic_slash" = "spell_power:arcane"
"simplyswords:sniffer_slam" = "spell_power:healing"
"simplyswords:stormlash" = "spell_power:lightning"
"simplyswords:verdant_trail" = "spell_power:healing"
"simplyswords:wing_buffet" = "spell_power:arcane"
"simplyswords:wolf_pack" = "spell_power:healing"

[ironsSpells]
enableCooldownReduction = true
basePower = 2.17

[ironsSpells.weaponManaCosts]
"simplyswords:arcanethyst" = 45
"simplyswords:awakened_lichblade" = 55
"simplyswords:bloodwake" = 15
"simplyswords:bramblethorn" = 45
"simplyswords:brimstone_claymore" = 45
"simplyswords:caelestis" = 150
"simplyswords:chompolotl" = 43
"simplyswords:dawnquiver" = 45
"simplyswords:dreadwhisper" = 45
"simplyswords:emberblade" = 15
"simplyswords:emberlash" = 20
"simplyswords:enigma" = 100
"simplyswords:flamewind" = 30
"simplyswords:frostfall" = 17
"simplyswords:gloampiercer" = 45
"simplyswords:harbinger" = 67
"simplyswords:hearthflame" = 25
"simplyswords:hiveheart" = 80
"simplyswords:icewhisper" = 45
"simplyswords:ionbound_stormscale" = 25
"simplyswords:livyatan" = 10
"simplyswords:magiblade" = 15
"simplyswords:magiscythe" = 77
"simplyswords:magispear" = 35
"simplyswords:mjolnir" = 55
"simplyswords:molten_edge" = 10
"simplyswords:ribboncleaver" = 10
"simplyswords:riftmane" = 60
"simplyswords:shadowsting" = 70
"simplyswords:soulkeeper" = 40
"simplyswords:soulpyre" = 115
"simplyswords:soulrender" = 10
"simplyswords:soulstalker" = 100
"simplyswords:soulstealer" = 60
"simplyswords:stars_edge" = 52
"simplyswords:stormbringer" = 10
"simplyswords:storms_edge" = 30
"simplyswords:stormscale" = 25
"simplyswords:sunfire" = 67
"simplyswords:tempest" = 20
"simplyswords:the_devourer" = 60
"simplyswords:thunderbrand" = 45
"simplyswords:toxic_longsword" = 0
"simplyswords:twisted_blade" = 20
"simplyswords:waxweaver" = 40
"simplyswords:whisperwind" = 40
"simplyswords:wickpiercer" = 3
"simplyswords:wraithfang" = 40
"simplyswords:wraithmaw" = 47

[ironsSpells.weaponAbilitySchools]
"simplyswords:brimstone_claymore" = "irons_spellbooks:fire"
"simplyswords:watcher_claymore" = "irons_spellbooks:blood"
"simplyswords:the_devourer" = "irons_spellbooks:eldritch"
"simplyswords:storms_edge" = "irons_spellbooks:lightning"
"simplyswords:stormscale" = "irons_spellbooks:lightning"
"simplyswords:awakened_stormscale" = "irons_spellbooks:lightning"
"simplyswords:ionbound_stormscale" = "irons_spellbooks:lightning"
"simplyswords:stormbringer" = "irons_spellbooks:lightning"
"simplyswords:bramblethorn" = "irons_spellbooks:nature"
"simplyswords:watching_warglaive" = "irons_spellbooks:blood"
"simplyswords:toxic_longsword" = "irons_spellbooks:nature"
"simplyswords:emberblade" = "irons_spellbooks:fire"
"simplyswords:hearthflame" = "irons_spellbooks:fire"
"simplyswords:soulkeeper" = "irons_spellbooks:blood"
"simplyswords:twisted_blade" = "irons_spellbooks:blood"
"simplyswords:soulstealer" = "irons_spellbooks:blood"
"simplyswords:soulrender" = "irons_spellbooks:blood"
"simplyswords:soulstalker" = "irons_spellbooks:eldritch"
"simplyswords:soulpyre" = "irons_spellbooks:blood"
"simplyswords:frostfall" = "irons_spellbooks:ice"
"simplyswords:molten_edge" = "irons_spellbooks:fire"
"simplyswords:livyatan/frost" = "irons_spellbooks:ice"
"simplyswords:livyatan/lightning" = "irons_spellbooks:lightning"
"simplyswords:icewhisper" = "irons_spellbooks:ice"
"simplyswords:arcanethyst" = "irons_spellbooks:eldritch"
"simplyswords:thunderbrand" = "irons_spellbooks:lightning"
"simplyswords:mjolnir" = "irons_spellbooks:lightning"
"simplyswords:slumbering_lichblade" = "irons_spellbooks:blood"
"simplyswords:waking_lichblade" = "irons_spellbooks:blood"
"simplyswords:awakened_lichblade" = "irons_spellbooks:blood"
"simplyswords:shadowsting" = "irons_spellbooks:ender"
"simplyswords:righteous_relic/damage" = "irons_spellbooks:fire"
"simplyswords:righteous_relic/healing" = "irons_spellbooks:holy"
"simplyswords:sunfire/damage" = "irons_spellbooks:fire"
"simplyswords:sunfire/healing" = "irons_spellbooks:holy"
"simplyswords:tainted_relic" = "irons_spellbooks:eldritch"
"simplyswords:harbinger" = "irons_spellbooks:eldritch"
"simplyswords:whisperwind" = "irons_spellbooks:evocation"
"simplyswords:dreadwhisper" = "irons_spellbooks:eldritch"
"simplyswords:emberlash" = "irons_spellbooks:fire"
"simplyswords:waxweaver" = "irons_spellbooks:fire"
"simplyswords:hiveheart" = "irons_spellbooks:nature"
"simplyswords:stars_edge" = "irons_spellbooks:ender"
"simplyswords:wickpiercer" = "irons_spellbooks:fire"
"simplyswords:gloampiercer" = "irons_spellbooks:eldritch"
"simplyswords:tempest/fire" = "irons_spellbooks:fire"
"simplyswords:tempest/frost" = "irons_spellbooks:ice"
"simplyswords:flamewind" = "irons_spellbooks:fire"
"simplyswords:magiscythe" = "irons_spellbooks:ender"
"simplyswords:enigma" = "irons_spellbooks:evocation"
"simplyswords:magispear" = "irons_spellbooks:evocation"
"simplyswords:magiblade" = "irons_spellbooks:eldritch"
"simplyswords:caelestis" = "irons_spellbooks:eldritch"
"simplyswords:dawnquiver" = "irons_spellbooks:holy"
"simplyswords:riftmane" = "irons_spellbooks:evocation"
"simplyswords:wraithfang" = "irons_spellbooks:ender"
"simplyswords:wraithmaw" = "irons_spellbooks:ender"
"simplyswords:bloodwake" = "irons_spellbooks:blood"
"simplyswords:chompolotl" = "irons_spellbooks:nature"
"simplyswords:dreadtide" = "irons_spellbooks:eldritch"

[ironsSpells.gemPowerSchools]
"simplyswords:banehead_swarm" = "irons_spellbooks:evocation"
"simplyswords:dancing_blades" = "irons_spellbooks:ender"
"simplyswords:dragon_maw" = "irons_spellbooks:fire"
"simplyswords:evocation" = "irons_spellbooks:evocation"
"simplyswords:faultline" = "irons_spellbooks:nature"
"simplyswords:goat_stampede" = "irons_spellbooks:nature"
"simplyswords:imbued" = "irons_spellbooks:ender"
"simplyswords:immolation" = "irons_spellbooks:fire"
"simplyswords:necromantic_arsenal" = "irons_spellbooks:blood"
"simplyswords:radiance" = "irons_spellbooks:fire"
"simplyswords:runic_slash" = "irons_spellbooks:ender"
"simplyswords:sniffer_slam" = "irons_spellbooks:nature"
"simplyswords:stormlash" = "irons_spellbooks:lightning"
"simplyswords:verdant_trail" = "irons_spellbooks:nature"
"simplyswords:wing_buffet" = "irons_spellbooks:evocation"
"simplyswords:wolf_pack" = "irons_spellbooks:nature"