#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Oct 01 13:45:41 CEST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=
enableShaders=false
